name: presc
description: A new Flutter project.

publish_to: 'none'

version: 1.4.2+22

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.2.13
  provider: ^6.0.4

  sqflite: ^2.2.0+2
  path_provider: ^2.0.2
  shared_preferences: ^2.0.7
  flutter_dotenv: ^5.0.2

  speech_to_text: ^7.0.0
  flutter_scale_tap: ^1.0.5
  flutter_keyboard_visibility: ^6.0.0
  fading_edge_scrollview: ^4.1.1
  flutter_colorpicker: ^1.0.3
  share_plus: ^11.0.0
  flutter_sharing_intent: ^1.1.1
  dots_indicator: ^4.0.1
  package_info_plus: ^8.3.0
  url_launcher: ^6.0.10
  flutter_staggered_animations: ^1.0.0
  sound_mode: ^3.0.0
  in_app_review: ^2.0.4
  vibration: ^3.1.3
  vibration_web: ^1.6.5
  http: ^1.2.2
  file_picker: ^10.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_utils: ^2.8.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/screenshot/
    - assets/images/en/
    - assets/images/en/screenshot/
    - .env

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icon.png"
  image_path_ios: "assets/images/icon_ios.png"
  adaptive_icon_background: "#FF6E42"
  adaptive_icon_foreground: "assets/images/foreground.png"

flutter_native_splash:
  image: "assets/images/splash.png"
  color: "#FF6E42"

flutter_intl:
  enabled: true
