name: Android DeployGate CI/CD

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    types: [ closed ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v5

      - name: install java 17.x
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: install flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.47.0'
          channel: 'stable'

      - name: install Android 16 SDK
        run: |
          sdkmanager_path=$(find "$HOME/Library/Android/sdk/cmdline-tools" -type f -name sdkmanager -print -quit)
          "$sdkmanager_path" "platforms;android-36" "build-tools;36.0.0"

      - name: cache flutter dependencies
        uses: actions/cache@v5
        with:
          path: |
            ~/.pub-cache
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      - name: setup env file
        env:
          BASE64_ENV_FILE: ${{ secrets.BASE64_ENV_FILE }}
        run: echo "$BASE64_ENV_FILE" | base64 --decode > .env

      - name: flutter dependencies install
        run: flutter pub get

      - run: flutter test

      - name: decode keystore
        env:
          ENCODED_DEBUG_KEYSTORE: ${{ secrets.ENCODED_DEBUG_KEYSTORE }}
        run: echo "$ENCODED_DEBUG_KEYSTORE" | base64 --decode > ~/.android/debug.keystore

      - name: build apk
        run: flutter build apk --flavor beta

      - name: upload apk artifact
        uses: actions/upload-artifact@v7
        with:
          name: presc-beta-apk
          path: build/app/outputs/flutter-apk/app-beta-release.apk
          retention-days: 7

      - name: distribute android apk
        env:
          DEPLOYGATE_API_KEY: ${{ secrets.DEPLOYGATE_API_KEY }}
          ANDROID_DISTRIBUTION_HASH: ${{ secrets.ANDROID_DISTRIBUTION_HASH }}
          DEPLOYGATE_USER: ${{ secrets.DEPLOYGATE_USER }}
        run: |
          curl \
            -H "Authorization: token $DEPLOYGATE_API_KEY" \
            -F "file=@build/app/outputs/flutter-apk/app-beta-release.apk" \
            -F "message=git:$(git rev-parse --short "$GITHUB_SHA")" \
            -F "distribution_name=${{ github.ref_name }}" \
            -F "release_note=new build" \
            -F "distribution_key=$ANDROID_DISTRIBUTION_HASH" \
            "https://deploygate.com/api/users/$DEPLOYGATE_USER/apps"
