name: iOS CI/CD

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    types: [ closed ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: show Xcode version
        run: xcodebuild -version
        
      - name: install flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.2'
          channel: 'stable'
          
      - name: cache flutter dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.pub-cache
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-flutter-
            
      - name: setup env file
        env:
          BASE64_ENV_FILE: ${{ secrets.BASE64_ENV_FILE }}
        run: echo $BASE64_ENV_FILE | base64 --decode > .env
        
      - name: flutter dependencies install
        run: flutter pub get
        
      - run: flutter test

      - name: import Code-Signing Certificates
        uses: Apple-Actions/import-codesign-certs@v2
        with:
          p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
          p12-password: ${{ secrets.CERTIFICATE_PASSWORD }}
          keychain: build_keychain

      - name: import Provisioning Profiles
        env:
          BASE64_PROVISIONING_PROFILE: ${{ secrets.BASE64_PROVISIONING_PROFILE }}
          BASE64_SHARE_EXTENSION_PROVISIONING_PROFILE: ${{ secrets.BASE64_SHARE_EXTENSION_PROVISIONING_PROFILE }}
        run: |
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          
          echo -n "$BASE64_PROVISIONING_PROFILE" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/main.mobileprovision
          echo -n "$BASE64_SHARE_EXTENSION_PROVISIONING_PROFILE" | base64 --decode > ~/Library/MobileDevice/Provisioning\ Profiles/share.mobileprovision
          
          MAIN_UUID=$(security cms -D -i ~/Library/MobileDevice/Provisioning\ Profiles/main.mobileprovision | plutil -extract UUID xml1 - -o - | sed -n 's/.*<string>\(.*\)<\/string>.*/\1/p')
          SHARE_UUID=$(security cms -D -i ~/Library/MobileDevice/Provisioning\ Profiles/share.mobileprovision | plutil -extract UUID xml1 - -o - | sed -n 's/.*<string>\(.*\)<\/string>.*/\1/p')
          
          mv ~/Library/MobileDevice/Provisioning\ Profiles/main.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/$MAIN_UUID.mobileprovision
          mv ~/Library/MobileDevice/Provisioning\ Profiles/share.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/$SHARE_UUID.mobileprovision
          
          echo "Main Profile UUID: $MAIN_UUID"
          echo "Share Profile UUID: $SHARE_UUID"
          ls -la ~/Library/MobileDevice/Provisioning\ Profiles/
          
          security cms -D -i ~/Library/MobileDevice/Provisioning\ Profiles/$MAIN_UUID.mobileprovision | plutil -extract Entitlements.application-identifier xml1 - -o - | sed -n 's/.*<string>\(.*\)<\/string>.*/\1/p'
          security cms -D -i ~/Library/MobileDevice/Provisioning\ Profiles/$SHARE_UUID.mobileprovision | plutil -extract Entitlements.application-identifier xml1 - -o - | sed -n 's/.*<string>\(.*\)<\/string>.*/\1/p'
          
      - name: import Export Options
        env:
          BASE64_EXPORT_OPTIONS: ${{ secrets.BASE64_EXPORT_OPTIONS }}
        run: echo -n "$BASE64_EXPORT_OPTIONS" | base64 --decode > ExportOptions.plist
        

      - name: configure manual signing and set profiles
        run: |
          # 手動署名に変更
          sed -i '' 's/ProvisioningStyle = Automatic;/ProvisioningStyle = Manual;/g' ios/Runner.xcodeproj/project.pbxproj
          sed -i '' 's/CODE_SIGN_STYLE = Automatic;/CODE_SIGN_STYLE = Manual;/g' ios/Runner.xcodeproj/project.pbxproj
          
          # 証明書タイプを正しく設定（すべてのパターンを変更）
          sed -i '' 's/"iOS Development"/"Apple Development"/g' ios/Runner.xcodeproj/project.pbxproj
          sed -i '' 's/CODE_SIGN_IDENTITY = "iPhone Developer";/CODE_SIGN_IDENTITY = "Apple Development";/g' ios/Runner.xcodeproj/project.pbxproj
          sed -i '' 's/CODE_SIGN_IDENTITY = "";/CODE_SIGN_IDENTITY = "Apple Development";/g' ios/Runner.xcodeproj/project.pbxproj
          
          # プロビジョニングプロファイルUUID取得
          MAIN_UUID=$(ls ~/Library/MobileDevice/Provisioning\ Profiles/ | grep -E "^[a-f0-9-]{36}\.mobileprovision$" | head -1 | sed 's/\.mobileprovision$//')
          SHARE_UUID=$(ls ~/Library/MobileDevice/Provisioning\ Profiles/ | grep -E "^[a-f0-9-]{36}\.mobileprovision$" | tail -1 | sed 's/\.mobileprovision$//')
          
          # Bundle IDで正しいプロファイルを判別
          MAIN_BUNDLE_ID=$(security cms -D -i ~/Library/MobileDevice/Provisioning\ Profiles/$MAIN_UUID.mobileprovision | plutil -extract Entitlements.application-identifier xml1 - -o - | sed -n 's/.*<string>9ADZZX385P\.\(.*\)<\/string>.*/\1/p')
          SHARE_BUNDLE_ID=$(security cms -D -i ~/Library/MobileDevice/Provisioning\ Profiles/$SHARE_UUID.mobileprovision | plutil -extract Entitlements.application-identifier xml1 - -o - | sed -n 's/.*<string>9ADZZX385P\.\(.*\)<\/string>.*/\1/p')
          
          echo "Main Bundle ID: $MAIN_BUNDLE_ID"
          echo "Share Bundle ID: $SHARE_BUNDLE_ID"
          
          # Share-Extensionプロファイルを判別して交換
          if [[ "$MAIN_BUNDLE_ID" == *"Share-Extension"* ]]; then
            TEMP_UUID=$MAIN_UUID
            MAIN_UUID=$SHARE_UUID
            SHARE_UUID=$TEMP_UUID
            echo "Swapped UUIDs: Main=$MAIN_UUID, Share=$SHARE_UUID"
          fi
          
          # プロビジョニングプロファイル設定（Runnerターゲットのみ）
          sed -i '' "s/PROVISIONING_PROFILE_SPECIFIER = \"\";/PROVISIONING_PROFILE_SPECIFIER = \"$MAIN_UUID\";/g" ios/Runner.xcodeproj/project.pbxproj
          sed -i '' "s/PROVISIONING_PROFILE = \"\";/PROVISIONING_PROFILE = \"$MAIN_UUID\";/g" ios/Runner.xcodeproj/project.pbxproj
          
          # チームID設定
          sed -i '' "s/DEVELOPMENT_TEAM = \"\";/DEVELOPMENT_TEAM = \"9ADZZX385P\";/g" ios/Runner.xcodeproj/project.pbxproj
          
          echo "Configuration completed with Main UUID: $MAIN_UUID for Runner target"
          
      - name: build iOS app
        run: |
          flutter clean
          flutter pub get
          cd ios && pod install
          cd ..
          flutter build ios --release --no-codesign
          
      - name: archive and export IPA
        run: |
          xcodebuild -workspace ios/Runner.xcworkspace \
            -scheme Runner \
            -sdk iphoneos \
            -configuration Release \
            archive \
            -archivePath build/ios/iphoneos/Runner.xcarchive
          
          xcodebuild -exportArchive \
            -archivePath build/ios/iphoneos/Runner.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath build/ios/iphoneos/
      
      - name: distribute iOS app
        env:
          DEPLOYGATE_API_KEY: ${{ secrets.DEPLOYGATE_API_KEY }}
          IOS_DISTRIBUTION_HASH: ${{ secrets.IOS_DISTRIBUTION_HASH }}
          DEPLOYGATE_USER: ${{ secrets.DEPLOYGATE_USER }}
        run: |
          GIT_HASH=$(git rev-parse --short $GITHUB_SHA)
          GIT_BRANCH=${GITHUB_REF##*/}
          curl \
            -H "Authorization: token $DEPLOYGATE_API_KEY" \
            -F "file=@build/ios/iphoneos/Presc.ipa" \
            -F "message=git:$GIT_HASH" \
            -F "distribution_name=$GIT_BRANCH" \
            -F "release_note=new ios build" \
            -F "distribution_key=$IOS_DISTRIBUTION_HASH" \
            "https://deploygate.com/api/users/$DEPLOYGATE_USER/apps"
